main: plugin.CX.Main
name: CX
version: 2.8.0
author: Xuyuan
api-version: 1.17
commands:
  chome:
    description: CHome for homes, death and shop
    aliases: ch
  cgroup:
    description: CGroup for group chats and private communication
    aliases: [ cgrp, cg ]
  cch:
    description: Shortcut for /cgroup channel
  say:
    description: Say message in chat. Usage | /say <message>
  cmenu:
    description: Operate CMenu
  ctab:
    description: Operates CTab
  enderchest:
    description: Access player enderchest
    aliases: ec
  invsee:
    description: Access player inventory
  beezooka:
    description: Fires a bee that explodes
#  anvil:
#    description: Opens Anvil GUI
permissions:
  chome.home:
    description: Teleport to home (chome home)
    default: true
  chome.sethome:
    description: Set player's home (chome sethome)
    default: true
  chome.death:
    description: Teleport to previous death point (chome death)
    default: true
  chome.shop:
    description: Teleport to shopping district (chome shop)
    default: true
  chome.setshop:
    description: Set global shop location
    default: op
  chome.admin:
    description: Allows player to set shopping district location, teleport to shop from all dimensions, teleport to other people's homes
    default: op
  cgroup.use:
    description: Allows a player to use CGroup functionality
    default: true
  cmenu.use:
    description: Allows player to operate CMenu
    default: op
  cx.allowSpecTp:
    desription: Allows player to teleport using spectator functions
    default: op
  cx.tablist:
    description: Operate CTab
    default: op
  cx.anvil:
    description: Use /anvil
    default: op
  cx.beezooka:
    description: Use /beezooka
    default: op
  cx.enderchest:
    description: Allows player to access enderchest of any player
    default: op
  cx.invsee:
    description: Use /invsee to access player inventory
    default: op
  cx.opName:
    description: Red name for ops
    default: op