main: plugin.CX.Main
name: CX
version: 2.2.1
author: Xuyuan
api-version: 1.17
commands:
  chome:
    description: CHome V2.1.6 for homes and death
    alias: ch
  cgroup:
    description: CGroup V2.1.6 for group chats and private communication
    aliases: [cgrp, cg]
  cch:
    description: Shortcut for /cgroup channel
  say:
    description: Say message in chat. Usage | /say <message>
permissions:
  chome.home:
    description: Allows player to use /chome home command
    default: true
  chome.death:
    description: Allows player to use /chome death command
    default: true
  chome.sethome:
    description: Allows player to set their home using /chome sethome
    default: true
  cgroup.use:
    description: Allows a player to use CGroup
    default: true