main: plugin.CX.Main
name: CX
version: 2.4.0
author: Xuyuan
api-version: 1.17
commands:
  chome:
    description: CHome for homes, death and shop
    alias: ch
  cgroup:
    description: CGroup for group chats and private communication
    aliases: [cgrp, cg]
  cch:
    description: Shortcut for /cgroup channel
  say:
    description: Say message in chat. Usage | /say <message>
    alias: s
permissions:
  chome.home:
    description: Allows player to teleport to home (chome home)
    default: true
  chome.home.others:
    description: Allows player to teleport to other's homes (chome home <target>)
    default: op
  chome.death:
    description: Allows player to teleport to previous death point (chome death)
    default: true
  chome.sethome:
    description: Allows player to set their home (chome sethome)
    default: true
  cgroup.use:
    description: Allows a player to use CGroup functionality
    default: true